### PR TITLE
Smoother transitions for the selected cover

### PR DESCRIPTION
**Pull request by Axce**
Hello again!
I added some code to make the sliding animation smoother for the 5 different views, hope you'll like it !
I will submit this to HexFlow LUC too.

### CODE REVIEW

**Comment by jimbob4000** [comment]
Hi @Axce , man you've got some skills!!

The animation is really smooth!
It works great when using the D-Pad, the only thing is it gets a bit blurry when using the analogue stick to scroll quickly.

I'm excited to see what you come up with next, it's great you've taken an interest in the project.
I'm not a fulltime developer, I've struggled with some bits.

**Comment by Axce** [comment]
About the blurriness, I don't know what can be done for that. Maybe animate less when the stick is used, but it would less pretty I think.

About the wide covers, I will try to take a look at it! It's striking when using the "flat, zoomed out" view, right? I find it not so bad in the other view types.

**Comment by jimbob4000** [comment]
The blurry thing is tricky. 
I think you're on the right lines, maybe while the analogue stick movement is detected, the zoom for the selected cover could be reduced?

I just tried the Aurora dashboard on my Xbox 360, it seems like they are doing something along those lines, difficult to tell.

**Comment by BlackSheepBoy69** [comment]
I made a pretty good attempt of fixing he N64 spacing awhile ago, I'll send it to you guys when I get a sec. I stopped on it because it feels kind of disorienting when you move from a N64 to a non-N64 and vice-versa so I stopped messing with it

**Comment by Axce** [comment]
New try !
I added a variable to check if we are using the stick, that is smoothed the same way as targetX. It prevents zooming while the stick is pushed. It's pretty nice now.

I'd like to make it work with the triggers and arrow-spamming too, by just detecting when we are moving "fast". But I'm still really confused about what the variables base_x, p, and master_index are.

I also used the space variable instead of 1, as @BlackSheepBoy69 suggested, it's a detail but it really feels nicer in some views.

**Comment by BlackSheepBoy69** [comment]
I haven't tried this new version, just clearing up some "esoteric" knowledge.

p is position

master_index is a remnant from SwitchView UI v0.1.2... for people that don't know, HexFlow Launcher (the official one) is based on SwitchView UI v0.1.2 secretly. Their code is almost identical. It doesn't really have a use in HexFlow or RetroFlow since it's always equal to variable p or something like that. master_index is where the camera is basicly. It's used in HexFlow LUC for SwitchView and Grid View (unreleased feature).

base_x is a variable that could probably be coded out completely if someone knew what they were doing and just use master_index instead. Formula for base_x is approximately: base_x = (curTotal - master_index + 1) * space

targetX is based on base_x and is used to calculate smooth movements ("drift"). If the app is going at 60 frames per second, then 60 times per second targetX will be made to be 10% closer to base_x. In Hexflow LUC, once it gets within 0.0001, it will stop calculating and just make them equal to save memory.

**Comment by jimbob4000** [comment]
@Axce I think it's better than before, what do you think?

I tried a couple of edits to make it feel a bit more responsive:
https://pastebin.com/FN0LeWSA

Slowed down the analogue scroll speed slightly to help with the blur, and made the smooth animation a bit quicker.
Not sure what you think, better or worse?

**Comment by BlackSheepBoy69** [comment]
@jimbob4000 please make a whole index.lua I want to try it out but am too lazy to find the 3 places where the code goes 👉👈

**Comment by jimbob4000** [comment]
@BlackSheepBoy69 here you go
[index.zip](https://github.com/jimbob4000/RetroFlow-Launcher/files/11236596/index.zip)

**Comment by jimbob4000** [comment]
@BlackSheepBoy69 , you may need to install the nightly build, then add the new attached index.lua
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

**Comment by Axce** [comment]
Yes, 1.7 definitely feels snappier!
About the scroll speed, I don't really feel the difference, but I can easily spot a game when I'm scrolling with the analog.
Should I add it to the pull request?
Kinda want to use the analog stick to control the scrolling speed now haha

**Comment by BlackSheepBoy69** [comment]
Try this I think it's a huge improvement on left-side view.

https://i.imgur.com/WBI7olT.jpg

**Comment by jimbob4000** [comment]
Cool, I'll have another look at the scroll speed change tomorrow to see if it makes a difference. 

No need to update the pull request unless you make some cool edits or fixes. 

I definitely think it's worth adding to the app. I'll probably add a setting to turn it off 
in case some people don't like it as much as us, but will have it on by default. 

Thanks so much for this, I really love it 👍

**Comment by jimbob4000** [comment]
Smooth scrolling has been added to the nightly build:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

It can be turned off by going to the theme settings.
I didn't change the scroll speed of the analogue sticks after all.

Thanks again @Axce

**Comment by jimbob4000** [comment]
One more thing, @Axce 

Is this French translation okay?
`Défilement fluide :`

**Comment by Axce** [comment]
Yes perfect !

**Comment by BlackSheepBoy69** [comment]
Upgraded left side view with a tiny bit of extra zoom.

<p></p>

`        -- left side view
        space = 1.5
        zoom = -0.6
        extray = -0.3
        camX = 1
        if x > space then
            rot = -0.5
            extraz = x * 0.8333				 --@@ (abs_side_factor + x) / 2 -----Simplify-----> x * 0.8333
            extrax = 0.6
        elseif x <= space and x > 0 then
            rot = -0.5 * abs_side_factor
            extraz = x * 0.8333 * dezoom_factor		 --@@ (abs_side_factor + x) / 2 -----Simplify-----> x * 0.8333
            extrax = 0.6 * abs_side_factor
        elseif (x < -space) or (x >= -space and x < 0) then
            rot = 0.5 * abs_side_factor
            extrax = -abs_side_factor
        end`

**Comment by jimbob4000** [comment]
It looks good, just not sure about the angle of the box on the left.

I was playing around with views too, and made this camera perspective one, it didn't make the release as it was more of an experiment. It's based on the default view, but with the camera position changed.

Video:
https://streamable.com/6sj4te

Pastebin:
https://pastebin.com/Q8FqPvKX

**Comment by BlackSheepBoy69** [comment]
To try it out making them all facing the same way, I think it would be like this for the last 4 lines:

`        elseif (x < -space) or (x >= -space and x < 0) then`
`          --rot = 0.5 * abs_side_factor`
`            rot = 0.5 * side_factor`
`            extrax = -abs_side_factor`
`        end`

**Comment by BlackSheepBoy69** [comment]
> I'm not a fulltime developer, so there's some parts of the HexFlow code I haven't figured out and tend to avoid.
I really wanted better box spacing for N64 and SNES games so they don't overlap (they look especially bad in the the 'All' category view), but I couldn't figure it out.

EVERYTHING related to this n64 fix is marked with "n64_fix"

https://streamable.com/801hgx

https://www.mediafire.com/file/9x996jd3apno4dd/n64_fix_HexFlow_Custom_v.1.9.9.9.9_ENGLISH_ONLY_toggle_with_select_button.vpk/file

There is a variable that might need some fine tuning which if I remember right was named something like n64_fatness.

Please note: this version is literally 99% ready for release. The only thing really missing is collections which I gotta bugtest, it's not in this version but it is all coded up.

It has the extreme-optimized grid view, it has loose cover match mode for Retro games, it has mass download of covers for every category and it reads in binary the PSP/PS1 game's ID just-in-time instead of using OneLua.

**Pull request closed without merging**
