### PR TITLE
Suggestion of alternative controls

### PR DESCRIPTION
**Pull request by Axce**
Hello, here's my suggestion of controls that would be easier, in my opinion :

**Down** to go to the next category
**Up** to go to the previous category
**Square** to show the Favorites/Recent/Collections menu

This code hasn't been tested (I didn't figure out how to build it), so it's just a draft.
If you think it's a good idea, I can edit the controls in the readme too.

### CODE REVIEW

**Comment by jimbob4000** [comment]
Hi again,

Thanks for the pull request, it's a nice idea and your code works, like you said, it's just the alphabet skip that would need to be mapped somehow too.

I've kind of got used to the controls and I'm pretty happy with where it's at, so I think I'll leave it alone for the time being, but appreciate the suggestion.

Thanks again

P.S. You're brave jumping into the code it's a bit of a mess :)

**Comment by Axce** [comment]
Ok I understand!
I will try to build my own fork!

Haha no problem, thankfully there were enough comments!

**Comment by jimbob4000** [comment]
You should try Hexflow Launcher unofficial custom too:

https://github.com/BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom

I think they have an option to use your control scheme. I think they use the start or select button (with L and R shoulders) for alphabetical skipping. 

If you need help, the index lua uses this language: 

https://rinnegatamante.github.io/lpp-vita/

The script lua uses this one:

http://onelua.x10.mx/vita/docs/en/

The script lua is used for functions like getting game names and extracting images from iso files.

**Comment by Axce** [comment]
Thanks for the help!
Noted!

**Pull request closed without merging**
